(()=>{'use strict';
const AREA='https://www.jma.go.jp/bosai/common/const/area.json',FEED='https://www.data.jma.go.jp/developer/xml/feed/extra_l.xml',DATA=/^https:\/\/www\.data\.jma\.go\.jp\/developer\/xml\/data\/\d{14}_\d+_VPWW53_(\d{6})\.xml$/;
const NS={c:'http://xml.kishou.go.jp/jmaxml1/',h:'http://xml.kishou.go.jp/jmaxml1/informationBasis1/',m:'http://xml.kishou.go.jp/jmaxml1/body/meteorology1/',a:'http://www.w3.org/2005/Atom'};
const copy={
'zh-CN':['附近天气 · JMA','手选地区；不使用定位。不是紧急预警。没有数据不表示安全。','府县预报区','市町村','请选择','查询 / 刷新','正在读取官方来源…','获取失败；风险未知。请查看 JMA。','没有匹配电文；索引不完整，不能推断安全。','来源快照 · 风险仍须查看官方信息','资料过期 · 风险未知','该电文系列已取消；不等于警报全部解除','地区未列于最新电文；风险未知','同时间电文冲突；风险未知','官方有效期已过；风险未知','发布时间','获取时间','原始风险名称 / 状态（JMA 日文）','JMA 原文','JMA 地区目录','来源：气象庁；本页按地区筛选，非官方制作。','本页缓存 / 请求间隔 45 秒；不自动轮询。','上一份电文 · 历史风险','地区目录加载失败；未查询警报。','当前索引只含有限历史记录，非完整实时服务。'],
'zh-TW':['附近天氣 · JMA','手選地區；不使用定位。不是緊急預警。沒有資料不表示安全。','府縣預報區','市町村','請選擇','查詢 / 重新整理','正在讀取官方來源…','取得失敗；風險未知。請查看 JMA。','沒有符合電文；索引不完整，不能推斷安全。','來源快照 · 風險仍須查看官方資訊','資料過期 · 風險未知','該電文系列已取消；不等於警報全部解除','地區未列於最新電文；風險未知','同時間電文衝突；風險未知','官方有效期已過；風險未知','發布時間','取得時間','原始風險名稱 / 狀態（JMA 日文）','JMA 原文','JMA 地區目錄','來源：気象庁；本頁按地區篩選，非官方製作。','本頁快取 / 請求間隔 45 秒；不自動輪詢。','上一份電文 · 歷史風險','地區目錄載入失敗；未查詢警報。','目前索引僅含有限歷史記錄，非完整即時服務。'],
ja:['近くの天気 · JMA','地域を手動選択。位置情報は使いません。緊急速報ではありません。データがなくても安全とは限りません。','府県予報区','市町村','選択してください','取得 / 更新','公式情報を取得中…','取得失敗。危険度は不明です。気象庁を確認してください。','対象電文なし。索引は不完全で、安全とは判断できません。','発表資料のスナップショット · 気象庁の情報も確認','資料が古い · 危険度不明','この電文系列は取消。警報の一斉解除ではありません','最新電文に地域なし · 危険度不明','同時刻の電文が競合 · 危険度不明','公式有効期間を経過 · 危険度不明','発表時刻','取得時刻','危険情報の名称 / 状態（気象庁原文）','気象庁の原文','気象庁の地域一覧','出典：気象庁。地域別に加工して表示。気象庁が制作した画面ではありません。','ページ内キャッシュ / 取得間隔45秒。自動ポーリングなし。','前の電文 · 過去の危険情報','地域一覧の取得失敗。警報は未取得。','索引に含まれる履歴は限定的です。完全なリアルタイム配信ではありません。'],
en:['Nearby weather · JMA','Select a region manually; no location access. Not emergency alerts. Missing data does not mean safe.','Forecast office area','Municipality','Choose a region','Fetch / refresh','Reading official sources…','Fetch failed; risk unknown. Check JMA.','No matching bulletin; the index is incomplete and does not establish safety.','Source snapshot · check official risk information','Stale information · risk unknown','This bulletin series was cancelled; this does not lift all warnings','Region absent from latest bulletin · risk unknown','Conflicting same-time revisions · risk unknown','Official validity elapsed · risk unknown','Published','Retrieved','Original risk name / status (JMA Japanese)','JMA original','JMA region catalogue','Source: JMA; filtered by Starnews, not a JMA-created page.','In-page cache / 45-second request interval; no automatic polling.','Previous bulletin · historical risks','Region catalogue failed; no warning fetch performed.','The index has limited history and is not a complete live service.']};
const lang=()=>document.documentElement.lang in copy?document.documentElement.lang:'en',t=i=>copy[lang()][i];
const children=(node,ns,name)=>Array.from(node.children).filter(x=>x.namespaceURI===ns&&x.localName===name);
function one(node,ns,name,required=true){const n=children(node,ns,name);if(n.length>1||required&&n.length!==1)throw Error('schema');return n[0]||null;}
function txt(node,ns,name,required=true){const n=one(node,ns,name,required),v=n?.textContent.trim()||'';if(v.length>12000||required&&!v)throw Error('schema');return v;}
function stamp(s){if(typeof s!=='string'||!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d+)?(?:Z|[+-]\d\d:\d\d)$/.test(s)||!Number.isFinite(Date.parse(s)))throw Error('timestamp');return Date.parse(s);}
function xml(text,limit){if(typeof text!=='string'||new TextEncoder().encode(text).length>limit||/<!\s*(DOCTYPE|ENTITY)/i.test(text)||/<\?(?!xml\s)/i.test(text))throw Error('unsafe_xml');const root=new DOMParser().parseFromString(text,'application/xml');if(root.getElementsByTagName('parsererror').length)throw Error('xml');let count=0,stack=[[root.documentElement,1]];while(stack.length){const [n,d]=stack.pop();if(++count>30000||d>40||n.namespaceURI==='http://www.w3.org/2001/XInclude')throw Error('xml_limit');for(const c of n.children)stack.push([c,d+1]);}return root.documentElement;}
function catalogue(data){if(!data||typeof data!=='object')throw Error('catalogue');const result={offices:{},cities:{}};for(const [code,o] of Object.entries(data.offices||{})){if(!/^\d{6}$/.test(code)||typeof o.name!=='string'||o.name.length>100)throw Error('catalogue');result.offices[code]={name:o.name,enName:typeof o.enName==='string'?o.enName.slice(0,100):''};}for(const [code,o] of Object.entries(data.class20s||{})){if(!/^\d{7}$/.test(code)||typeof o.name!=='string'||o.name.length>100)throw Error('catalogue');const p=data.class15s?.[o.parent],q=data.class10s?.[p?.parent],office=q?.parent;if(!result.offices[office])throw Error('catalogue');result.cities[code]={name:o.name,enName:typeof o.enName==='string'?o.enName.slice(0,100):'',office};}if(Object.keys(result.offices).length>100||Object.keys(result.cities).length>3000||!Object.keys(result.cities).length)throw Error('catalogue');return result;}
function feed(text,office){if(!/^\d{6}$/.test(office))throw Error('region');const root=xml(text,4000000);if(root.namespaceURI!==NS.a||root.localName!=='feed')throw Error('feed');const links=new Map();for(const e of children(root,NS.a,'entry')){const updated=stamp(txt(e,NS.a,'updated'));for(const l of children(e,NS.a,'link')){const u=l.getAttribute('href')||'',m=u.match(DATA);if(m&&m[1]===office)links.set(u,Math.max(updated,links.get(u)||0));}}return Array.from(links).sort((a,b)=>b[1]-a[1]).slice(0,2).map(x=>x[0]);}
function report(text,url,fetchedAt){if(!DATA.test(url))throw Error('url');const root=xml(text,1000000);if(root.namespaceURI!==NS.c||root.localName!=='Report')throw Error('schema');const c=one(root,NS.c,'Control'),h=one(root,NS.h,'Head'),body=one(root,NS.m,'Body',false);const title=txt(c,NS.c,'Title'),status=txt(c,NS.c,'Status');if(title!=='気象特別警報・警報・注意報'||status!=='通常'||txt(h,NS.h,'InfoKind')!=='気象警報・注意報'||txt(h,NS.h,'InfoKindVersion')!=='1.1_2')throw Error('schema');const type=txt(h,NS.h,'InfoType');if(!['発表','訂正','取消'].includes(type))throw Error('schema');const fetched=stamp(fetchedAt),updated=txt(c,NS.c,'DateTime'),published=txt(h,NS.h,'ReportDateTime');if(stamp(updated)>fetched+300000||stamp(published)>fetched+300000)throw Error('future');const valid=txt(h,NS.h,'ValidDateTime',false);if(valid)stamp(valid);const risks=new Map();if(body)for(const w of children(body,NS.m,'Warning')){if(w.getAttribute('type')!=='気象警報・注意報（市町村等）')continue;for(const item of children(w,NS.m,'Item')){const area=one(item,NS.m,'Area'),code=txt(area,NS.m,'Code'),name=txt(area,NS.m,'Name');if(!/^\d{7}$/.test(code))throw Error('region');for(const k of children(item,NS.m,'Kind')){const risk=Object.freeze({area_code:code,area_name:name,name:txt(k,NS.m,'Name'),code:txt(k,NS.m,'Code'),status:txt(k,NS.m,'Status')}),key=code+':'+risk.code;if(risks.has(key)&&JSON.stringify(risks.get(key))!==JSON.stringify(risk))throw Error('risk_conflict');risks.set(key,risk);}}}if(type!=='取消'&&!risks.size)throw Error('empty_schema');const r={source_url:url,published_at:published,source_updated_at:updated,fetched_at:fetchedAt,valid_until:valid,info_type:type,series:JSON.stringify([title,txt(c,NS.c,'EditorialOffice'),status,txt(h,NS.h,'EventID',false)]),risks:Object.freeze(Array.from(risks.values()))};r.signature=JSON.stringify([r.series,updated,published,valid,type,r.risks]);return Object.freeze(r);}
function reduce(previous,b,code){if(!/^\d{7}$/.test(code))throw Error('region');if(previous&&(previous.code!==code||previous.latest.series!==b.series))throw Error('series');const risks=b.risks.filter(r=>r.area_code===code);if(previous){if(stamp(b.source_updated_at)<stamp(previous.latest.source_updated_at)||b.signature===previous.latest.signature)return previous;if(stamp(b.source_updated_at)===stamp(previous.latest.source_updated_at))return Object.freeze({...previous,conflict:true});}if(!previous&&!risks.length&&b.info_type!=='取消')return Object.freeze({latest:b,code,risks:Object.freeze([]),previousRisks:Object.freeze([]),conflict:false});return Object.freeze({latest:b,code,risks:Object.freeze(b.info_type==='取消'?[]:risks),previousRisks:previous?.risks.length?previous.risks:previous?.previousRisks||Object.freeze([]),conflict:false});}
function state(s,now=Date.now()){if(!s)return 'missing';if(s.conflict)return 'conflict';if(s.latest.info_type==='取消')return 'cancelled';if(s.latest.valid_until&&now>=stamp(s.latest.valid_until))return 'expired';if(now-Math.min(stamp(s.latest.fetched_at),stamp(s.latest.source_updated_at))>1800000)return 'stale';return s.risks.length?'snapshot':'absent';}
const cache=new Map();let lastRequest=-Infinity;
async function read(url,limit,signal){if(url!==AREA&&url!==FEED&&!DATA.test(url))throw Error('url');const cached=cache.get(url);if(cached&&Date.now()-cached.at<180000)return cached;const ctrl=new AbortController(),abort=()=>ctrl.abort(),timer=setTimeout(abort,10000);signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)ctrl.abort();try{const response=await fetch(url,{signal:ctrl.signal,credentials:'omit',redirect:'error',cache:'no-store'});if(!response.ok)throw Error('http');const reader=response.body.getReader(),decoder=new TextDecoder('utf-8',{fatal:true});let size=0,text='';try{while(true){const p=await reader.read();if(p.done)break;size+=p.value.length;if(size>limit)throw Error('size');text+=decoder.decode(p.value,{stream:true});}text+=decoder.decode();}finally{await reader.cancel().catch(()=>{});}if(ctrl.signal.aborted)throw Error('cancelled');const value={text,at:Date.now()};cache.set(url,value);while(cache.size>8)cache.delete(cache.keys().next().value);return value;}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);}}
window.StarnewsJMA=Object.freeze({catalogue,feed,report,reduce,state,read,AREA,FEED});
const section=document.getElementById('jmaEvents');if(!section)return;let areas=null,selection=null,selectedOffice='',selectedCity='',notice='idle',generation=0,controller=null,busy=false;
function invalidate(){generation++;controller?.abort();controller=null;busy=false;selection=null;notice='idle';}
function el(tag,text){const e=document.createElement(tag);if(text)e.textContent=text;return e;}
function render(){section.replaceChildren();const title=el('h2',t(0)),description=el('p',t(1));section.append(title,description);const controls=el('div');controls.className='jma-controls';function select(id,label,options,value){const wrap=el('label',label),s=el('select');s.id=id;const blank=el('option',t(4));blank.value='';s.append(blank);for(const [code,a] of options){const o=el('option',(lang()==='en'&&a.enName?a.enName:a.name)+' · '+code);o.value=code;s.append(o);}s.value=value;wrap.append(s);controls.append(wrap);return s;}const office=select('jmaOffice',t(2),Object.entries(areas?.offices||{}),selectedOffice);const city=select('jmaCity',t(3),Object.entries(areas?.cities||{}).filter(([,c])=>c.office===selectedOffice),selectedCity);office.disabled=!areas;city.disabled=!selectedOffice;office.onchange=()=>{invalidate();selectedOffice=office.value;selectedCity='';render();};city.onchange=()=>{invalidate();selectedCity=city.value;render();};const button=el('button',t(5));button.id='jmaRefresh';button.type='button';button.disabled=busy||!selectedCity;button.onclick=load;controls.append(button);section.append(controls);const status=el('p');status.id='jmaStatus';status.setAttribute('role','status');const map={loading:6,error:7,missing:8,snapshot:9,stale:10,cancelled:11,absent:12,conflict:13,expired:14,catalogue_error:23,throttle:21,idle:24};status.textContent=t(map[notice]??24);if(selection&&notice==='throttle')status.textContent+=' '+t(map[state(selection)]??24);section.append(status);if(selection){const b=selection.latest,meta=el('p',t(15)+': '+b.published_at+' · '+t(16)+': '+b.fetched_at);meta.className='jma-times';section.append(el('p',t(18)+': '+b.info_type));const link=el('a',t(18));link.href=b.source_url;link.target='_blank';link.rel='noopener noreferrer';section.append(meta,link,el('p',t(17)));const list=el('ul');list.id='jmaRiskList';for(const r of selection.risks)list.append(el('li',r.name+' ['+r.code+'] · '+r.status+' · '+r.area_name+' ['+r.area_code+']'));section.append(list);if(selection.previousRisks.length){const details=el('details');details.append(el('summary',t(22)));const previous=el('ul');for(const r of selection.previousRisks)previous.append(el('li',r.name+' ['+r.code+'] · '+r.status+' · '+r.area_name));details.append(previous);section.append(details);}if(state(selection)==='cancelled'&&Date.now()-stamp(b.source_updated_at)>1800000)section.append(el('p',t(10)));}const source=el('p',t(20)+' '+t(24)),guide=el('a',t(19));guide.href=AREA;guide.target='_blank';guide.rel='noopener noreferrer';source.append(document.createTextNode(' '),guide);const warningLink=el('a','JMA · '+t(0));warningLink.href='https://www.jma.go.jp/bosai/warning/';warningLink.target='_blank';warningLink.rel='noopener noreferrer';source.append(document.createTextNode(' · '),warningLink);section.append(source);}
async function load(){if(busy||!areas?.cities[selectedCity]||areas.cities[selectedCity].office!==selectedOffice)return;if(Date.now()-lastRequest<45000){notice='throttle';render();return;}lastRequest=Date.now();const version=++generation,code=selectedCity,office=selectedOffice;controller=new AbortController();const signal=controller.signal;busy=true;notice='loading';render();try{const f=await read(FEED,4000000,signal),links=feed(f.text,office);if(!links.length){if(version===generation){selection=null;notice='missing';}return;}const first=await read(links[0],1000000,signal),latest=report(first.text,links[0],new Date(first.at).toISOString());let result=null;if(latest.info_type==='取消'&&links[1]){const prior=await read(links[1],1000000,signal),old=report(prior.text,links[1],new Date(prior.at).toISOString());if(old.series===latest.series&&old.info_type!=='取消')result=reduce(null,old,code);}if(selection&&selection.latest.series===latest.series&&selection.code===code)result=selection;result=reduce(result,latest,code);if(version===generation){selection=result;notice=state(result);}}catch{if(version===generation){selection=null;notice='error';}}finally{if(version===generation){busy=false;controller=null;render();}}}
render();read(AREA,1000000).then(data=>{areas=catalogue(JSON.parse(data.text));render();}).catch(()=>{notice='catalogue_error';render();});new MutationObserver(()=>render()).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});window.addEventListener('pagehide',()=>invalidate());
})();
