(() => {
  'use strict';
  const dictionaries = {
    'zh-CN': {title:'个人 AI',open:'个人 AI · 分析与偏好',disabled:'私人 AI 服务尚未配置。公开新闻与本机偏好仍可正常使用。',endpoint:'私人服务地址',connect:'连接服务',email:'登录邮箱',login:'发送登录链接',sent:'请在本人邮箱中打开登录链接。',logout:'退出登录',provider:'AI 提供商',key:'你的 API Key',keyNote:'仅经 HTTPS 发送到所选私人服务，加密保存；不会写入公开网页或浏览器存储。请只连接你信任的服务。',saveKey:'加密保存密钥',removeKey:'删除此提供商密钥',question:'问题或扩展阅读方向',ask:'分析当前报道',consent:'同意将本次问题、当前公开报道、本人保存的偏好与记忆，以及最近6条本人对话发送给所选 AI 提供商。AI 回答可能出错，不构成事实核验。',history:'查看私人对话历史',clear:'删除对话历史',export:'导出我的数据',remove:'删除网站个人数据',confirm:'确认删除网站个人数据？密钥、偏好、记忆、对话都会删除；认证服务账号需另外删除。',preferences:'同步当前语言与关注领域',memory:'本人明确保存的阅读偏好 / 记忆',savePrefs:'保存私人偏好与记忆',ready:'服务已连接，请登录。',signed:'已登录 · 本次会话仅保存在内存',wait:'正在处理…',error:'请求未完成，请重试或检查服务配置。',needLogin:'请先登录本人账户。',noArticle:'请先选择一条报道。',done:'已完成',close:'关闭',privacy:'公共简报不接收个人数据。私人服务保存你明确提交的偏好、记忆和对话。退出将清除当前会话；重新打开页面需重新登录。删除网站数据不会删除认证服务账户。',recommended:'依私人偏好推荐本期新闻',recs:'推荐新闻',notReady:'服务尚未启用，请查看部署说明。',safeEndpoint:'请输入有效的 HTTPS 服务地址。',missingConsent:'请先同意本次数据发送。',keys:'已保存提供商',pool:'本站公共 AI 额度可用，受每用户及全站限额限制。',noPool:'没有公共 AI 额度，需要本人 BYOK。',local:'服务地址只保存在本机；登录令牌和密钥不保存在本机。'},
    'zh-TW': {title:'個人 AI',open:'個人 AI · 分析與偏好',disabled:'私人 AI 服務尚未設定。公開新聞與本機偏好仍可正常使用。',endpoint:'私人服務位址',connect:'連接服務',email:'登入信箱',login:'寄送登入連結',sent:'請在本人信箱開啟登入連結。',logout:'登出',provider:'AI 提供商',key:'你的 API Key',keyNote:'僅透過 HTTPS 傳送至所選私人服務並加密保存；不會寫入公開網頁或瀏覽器儲存。請只連接可信服務。',saveKey:'加密保存金鑰',removeKey:'刪除此提供商金鑰',question:'問題或延伸閱讀方向',ask:'分析目前報導',consent:'同意將本次問題、公開報導、本人偏好與記憶及最近6則本人對話傳送給所選 AI 提供商。AI 回答可能出錯，不等於事實查核。',history:'查看私人對話紀錄',clear:'刪除對話紀錄',export:'匯出我的資料',remove:'刪除網站個人資料',confirm:'確認刪除金鑰、偏好、記憶與對話？認證服務帳號需另行刪除。',preferences:'同步目前語言與關注領域',memory:'本人明確保存的閱讀偏好 / 記憶',savePrefs:'保存私人偏好與記憶',ready:'服務已連接，請登入。',signed:'已登入 · 本次工作階段僅存在記憶體',wait:'處理中…',error:'請求未完成，請重試或檢查服務設定。',needLogin:'請先登入本人帳號。',noArticle:'請先選擇一則報導。',done:'已完成',close:'關閉',privacy:'公共簡報不接收個人資料。私人服務保存你明確提交的偏好、記憶與對話。登出會清除本次工作階段；重新開啟頁面需重新登入。刪除網站資料不會刪除認證服務帳號。',recommended:'依私人偏好推薦本期新聞',recs:'推薦新聞',notReady:'服務尚未啟用，請查看部署說明。',safeEndpoint:'請輸入有效的 HTTPS 服務位址。',missingConsent:'請先同意本次資料傳送。',keys:'已保存提供商',pool:'本站公共 AI 額度可用，受個人與全站限制。',noPool:'沒有公共 AI 額度，需要本人 BYOK。',local:'服務位址只保存在本機；登入令牌與金鑰不保存在本機。'},
    ja:{title:'パーソナル AI',open:'パーソナル AI · 分析と設定',disabled:'個人向け AI サービスは未設定です。公開ニュースと端末の設定は利用できます。',endpoint:'個人向けサービス URL',connect:'接続',email:'ログイン用メール',login:'ログインリンクを送信',sent:'ご本人のメールでログインリンクを開いてください。',logout:'ログアウト',provider:'AI プロバイダー',key:'あなたの API Key',keyNote:'選択したサービスに HTTPS で送信し、暗号化して保存します。公開ページやブラウザには保存しません。信頼できるサービスのみ接続してください。',saveKey:'キーを暗号化して保存',removeKey:'このキーを削除',question:'質問・さらに知りたいこと',ask:'この記事を分析',consent:'今回の質問・公開記事・本人の設定とメモリ・直近6件の会話を選択した AI プロバイダーに送信することに同意します。AI の回答には誤りがあり、事実確認ではありません。',history:'個人の会話履歴',clear:'会話履歴を削除',export:'自分のデータを書き出す',remove:'サイトの個人データを削除',confirm:'キー・設定・メモリ・会話を削除しますか？認証サービスのアカウントは別途削除が必要です。',preferences:'現在の言語と関心分野を同期',memory:'明示的に保存する読書設定・メモリ',savePrefs:'設定とメモリを保存',ready:'接続しました。ログインしてください。',signed:'ログイン済み · セッションはメモリ内のみ',wait:'処理中…',error:'処理できませんでした。再試行または設定をご確認ください。',needLogin:'本人のアカウントでログインしてください。',noArticle:'先に記事を選んでください。',done:'完了',close:'閉じる',privacy:'公開ニュースには個人データを送りません。個人サービスには明示的に送信した設定・メモリ・会話を保存します。ログアウトでセッションを消去し、再読み込み後は再ログインが必要です。サイトのデータ削除は認証アカウントの削除を含みません。',recommended:'設定に基づく記事の推薦',recs:'おすすめ記事',notReady:'サービスはまだ有効ではありません。導入手順をご確認ください。',safeEndpoint:'有効な HTTPS URL を入力してください。',missingConsent:'今回の送信に同意してください。',keys:'保存済みプロバイダー',pool:'サイトの共有 AI 枠を利用できます。個人・全体の上限があります。',noPool:'共有 AI 枠はありません。本人の BYOK が必要です。',local:'URL のみ端末に保存。トークンとキーは端末に保存しません。'},
    en:{title:'Personal AI',open:'Personal AI · analysis & preferences',disabled:'The private AI service is not configured. Public news and local preferences remain available.',endpoint:'Private service URL',connect:'Connect service',email:'Sign-in email',login:'Send sign-in link',sent:'Open the sign-in link in your own email.',logout:'Sign out',provider:'AI provider',key:'Your API key',keyNote:'Sent over HTTPS to the selected private service and encrypted there. Never saved in the public site or browser storage. Connect only to a service you trust.',saveKey:'Save encrypted key',removeKey:'Delete this provider key',question:'Question or further reading',ask:'Analyze current article',consent:'I agree to send this question, the public article, my saved preferences and memory, and my last 6 chat messages to the selected AI provider. AI answers may be wrong and are not fact verification.',history:'Read private chat history',clear:'Delete chat history',export:'Export my data',remove:'Delete site personal data',confirm:'Delete site keys, preferences, memory and chats? The authentication account must be deleted separately.',preferences:'Sync current language and topics',memory:'Reading preferences / memory I explicitly save',savePrefs:'Save private preferences & memory',ready:'Service connected. Please sign in.',signed:'Signed in · session held only in memory',wait:'Working…',error:'Request failed. Retry or check the service configuration.',needLogin:'Sign in to your own account first.',noArticle:'Select an article first.',done:'Done',close:'Close',privacy:'Public briefs receive no personal data. The private service stores preferences, memory and chats you explicitly submit. Signing out clears this session; reopening requires sign-in. Deleting site data does not delete the authentication account.',recommended:'Recommend this edition using my preferences',recs:'Recommended articles',notReady:'Service is not enabled. See deployment instructions.',safeEndpoint:'Enter a valid HTTPS service URL.',missingConsent:'Agree to this transmission first.',keys:'Saved providers',pool:'A shared site AI allowance is available, with per-user and global limits.',noPool:'No shared AI allowance. Bring your own key.',local:'Only the service URL is stored on this device. Session tokens and keys are not stored.'}
  };
  const $=id=>document.getElementById(id), bridge=()=>window.StarnewsBridge||{};
  const locale=()=>bridge().getLocale?.()||document.documentElement.lang||'zh-CN';
  const tr=k=>(dictionaries[locale()]||dictionaries.en)[k]||k;
  const mk=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e;};
  let endpoint='', health=null, token='', expires=0, lastFocus=null, busy=false, callbackEmail='';
  try{endpoint=window.__STARNEWS_PRIVATE_CONFIG?.endpoint||localStorage.getItem('starnews:private:endpoint')||'';}catch{}
  // Consume callback tokens immediately; never persist them or retain them in a shareable URL.
  try{const h=new URLSearchParams(location.hash.slice(1));if(h.has('access_token')){const query=new URLSearchParams(location.search),pending=JSON.parse(localStorage.getItem('starnews:private:login')||'null');if(pending&&pending.state===query.get('login_state')&&pending.endpoint===endpoint&&pending.expires>Date.now()){token=h.get('access_token')||'';callbackEmail=pending.email;expires=Date.now()+Math.min(3600,Number(h.get('expires_in'))||3600)*1000;}localStorage.removeItem('starnews:private:login');query.delete('login_state');history.replaceState(null,'',location.pathname+(query.size?'?'+query.toString():''));}}catch{}
  const overlay=mk('div');overlay.id='personalAIOverlay';overlay.className='personal-ai-overlay';overlay.hidden=true;
  const panel=mk('section');panel.className='personal-ai-panel';panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-labelledby','personalAITitle');
  overlay.append(panel);document.body.append(overlay);
  function status(text){$('personalAIStatus').textContent=text;}
  function action(text,fn,cls){const b=mk('button',text);b.type='button';if(cls)b.className=cls;b.addEventListener('click',()=>run(fn));return b;}
  async function run(fn){if(busy)return;busy=true;status(tr('wait'));try{await fn();}catch(e){status(e.localMessage||tr('error'));}finally{busy=false;}}
  function field(form,id,label,type='text'){const l=mk('label',label);l.htmlFor=id;const i=mk(type==='textarea'?'textarea':'input');i.id=id;if(type!=='textarea')i.type=type;i.autocomplete=type==='password'?'off':type==='email'?'email':'off';form.append(l,i);return i;}
  function fail(k){const e=new Error(k);e.localMessage=tr(k);throw e;}
  function validEndpoint(raw){try{const u=new URL(raw);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash)fail('safeEndpoint');return u.origin+u.pathname.replace(/\/$/,'');}catch{fail('safeEndpoint');}}
  async function request(path,method='GET',body){if(!token||Date.now()>=expires){signout();fail('needLogin');}const res=await fetch(endpoint+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store',credentials:'omit',signal:AbortSignal.timeout(30000)});if(res.status===401){signout();fail('needLogin');}if(!res.ok)throw new Error('private request failed');return res.json();}
  function syncSigned(){const signed=Boolean(token&&Date.now()<expires);$('personalAISigned').hidden=!signed;$('personalAILogin').hidden=signed;status(tr(signed?'signed':'ready'));}
  async function connect(){endpoint=validEndpoint($('personalAIEndpoint').value);token='';expires=0;health=null;await loadHealth();try{localStorage.setItem('starnews:private:endpoint',endpoint);}catch{}syncSigned();}
  async function loadHealth(){const r=await fetch(endpoint+'/health',{cache:'no-store',credentials:'omit',signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error('health failed');const h=await r.json();if(!h.enabled||!h.auth?.url||!h.auth?.anonKey)fail('notReady');const authURL=new URL(h.auth.url);if(authURL.protocol!=='https:'||!authURL.hostname.endsWith('.supabase.co'))throw new Error('invalid auth');health=h;$('personalAIAuth').hidden=false;$('personalAIPool').textContent=tr(h.publicPool?'pool':'noPool');}
  async function login(){if(!health)fail('notReady');const email=$('personalAIEmail').value.trim();if(!email||!$('personalAIEmail').checkValidity())throw new Error('invalid email');const state=crypto.randomUUID();try{localStorage.setItem('starnews:private:login',JSON.stringify({state,email,endpoint,expires:Date.now()+15*60000}));}catch{throw new Error('sign-in storage unavailable');}const redirect=location.origin+location.pathname+'?login_state='+encodeURIComponent(state);const r=await fetch(health.auth.url+'/auth/v1/otp?redirect_to='+encodeURIComponent(redirect),{method:'POST',headers:{apikey:health.auth.anonKey,'Content-Type':'application/json'},body:JSON.stringify({email,create_user:true}),credentials:'omit',signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error('sign in failed');status(tr('sent'));}
  function signout(){token='';expires=0;callbackEmail='';try{localStorage.removeItem('starnews:private:login');}catch{}$('personalAIKey').value='';$('personalAIMemory').value='';$('personalAIQuestion').value='';$('personalAIAnswer').textContent='';$('personalAIHistory').textContent='';$('personalAISigned').hidden=true;$('personalAILogin').hidden=false;}
  async function prefs(){const d=await request('/preferences');$('personalAIMemory').value=d.preferences?.memory||'';$('personalAIKeys').textContent=tr('keys')+': '+(d.keys||[]).join(', ');}
  function build(){panel.replaceChildren();const head=mk('header');head.className='personal-ai-head';const title=mk('h2',tr('title'));title.id='personalAITitle';head.append(title,action(tr('close'),async()=>close()));panel.append(head);const stat=mk('p');stat.id='personalAIStatus';stat.className='personal-ai-status';stat.setAttribute('role','status');panel.append(stat,mk('p',tr('disabled')));const privacy=mk('p',tr('privacy'));privacy.className='personal-ai-privacy';panel.append(privacy);
    const conn=mk('form');conn.addEventListener('submit',e=>{e.preventDefault();run(connect);});const url=field(conn,'personalAIEndpoint',tr('endpoint'),'url');url.value=endpoint;const cb=mk('button',tr('connect'));cb.type='submit';conn.append(mk('small',tr('local')),cb);panel.append(conn);
    const auth=mk('div');auth.id='personalAIAuth';auth.hidden=true;const lf=mk('form');lf.id='personalAILogin';lf.addEventListener('submit',e=>{e.preventDefault();run(login);});field(lf,'personalAIEmail',tr('email'),'email');const lb=mk('button',tr('login'));lb.type='submit';lf.append(lb);auth.append(lf);
    const signed=mk('div');signed.id='personalAISigned';signed.hidden=true;signed.append(action(tr('logout'),async()=>{signout();status(tr('ready'));}));const pool=mk('p');pool.id='personalAIPool';signed.append(pool);
    const keyForm=mk('form');keyForm.addEventListener('submit',e=>e.preventDefault());const pl=mk('label',tr('provider'));pl.htmlFor='personalAIProvider';const providers=mk('select');providers.id='personalAIProvider';for(const p of ['groq','gemini','openrouter','openai']){const o=mk('option',p);o.value=p;providers.append(o);}keyForm.append(pl,providers);const key=field(keyForm,'personalAIKey',tr('key'),'password');key.maxLength=512;const keys=mk('small');keys.id='personalAIKeys';keyForm.append(mk('small',tr('keyNote')),keys,action(tr('saveKey'),async()=>{const v=key.value;key.value='';if(!v)throw new Error('empty key');await request('/keys/'+providers.value,'PUT',{key:v});await prefs();status(tr('done'));}),action(tr('removeKey'),async()=>{await request('/keys/'+providers.value,'DELETE');await prefs();status(tr('done'));}));signed.append(keyForm);
    const pf=mk('form');pf.addEventListener('submit',e=>e.preventDefault());const memory=field(pf,'personalAIMemory',tr('memory'),'textarea');memory.maxLength=2000;pf.append(action(tr('savePrefs'),async()=>{await request('/preferences','PUT',{language:locale(),topics:bridge().getTopics?.()||[],memory:memory.value});status(tr('done'));}),mk('small',tr('preferences')));signed.append(pf);
    const qf=mk('form');qf.addEventListener('submit',e=>e.preventDefault());const q=field(qf,'personalAIQuestion',tr('question'),'textarea');q.maxLength=2000;const consent=mk('label');consent.className='personal-ai-confirm';const ci=mk('input');ci.type='checkbox';ci.id='personalAIConsent';consent.append(ci,mk('span',tr('consent')));qf.append(consent,action(tr('ask'),async()=>{if(!ci.checked)fail('missingConsent');const article=bridge().getArticle?.();if(!article?.title)fail('noArticle');const d=await request('/chat','POST',{provider:providers.value,message:q.value||tr('ask'),language:locale(),article});$('personalAIAnswer').textContent=d.answer;status(tr('done'));}));signed.append(qf);const answer=mk('div');answer.id='personalAIAnswer';answer.className='personal-ai-answer';answer.setAttribute('aria-live','polite');signed.append(answer);
    const actions=mk('div');actions.className='personal-ai-actions';actions.append(action(tr('recommended'),async()=>{const articles=bridge().getArticles?.()||[];const d=await request('/recommendations','POST',{articles,language:locale()});const map=new Map(articles.map(a=>[a.id,a.title]));answer.textContent=tr('recs')+'\n'+(d.ids||[]).map(id=>map.get(id)||'').filter(Boolean).join('\n');status(tr('done'));}),action(tr('history'),async()=>{const d=await request('/history');$('personalAIHistory').textContent=(d.history||[]).map(h=>h.role+': '+h.content).join('\n\n');status(tr('done'));}),action(tr('clear'),async()=>{await request('/history','DELETE');$('personalAIHistory').textContent='';answer.textContent='';status(tr('done'));}),action(tr('export'),async()=>{const [p,h]=await Promise.all([request('/preferences'),request('/history')]);const blob=new Blob([JSON.stringify({preferences:p.preferences,history:h.history},null,2)],{type:'application/json'});const a=mk('a');a.href=URL.createObjectURL(blob);a.download='starnews-personal-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);status(tr('done'));}),action(tr('remove'),async()=>{if(!confirm(tr('confirm'))){status(tr('signed'));return;}await request('/account','DELETE');signout();status(tr('done'));},'danger'));signed.append(actions);const hist=mk('div');hist.id='personalAIHistory';hist.className='personal-ai-history';signed.append(hist);auth.append(signed);panel.append(auth);status(tr('disabled'));
  }
  function close(){overlay.hidden=true;document.body.style.overflow='';for(const el of Array.from(document.body.children))if(el.dataset.personalAIInert==='yes'){el.inert=false;delete el.dataset.personalAIInert;}lastFocus?.focus?.();}
  async function open(){lastFocus=document.activeElement;overlay.hidden=false;document.body.style.overflow='hidden';for(const el of Array.from(document.body.children))if(el!==overlay&&!el.inert){el.inert=true;el.dataset.personalAIInert='yes';}panel.querySelector('button').focus();if(endpoint){await loadHealth();if(token&&callbackEmail){const r=await fetch(health.auth.url+'/auth/v1/user',{headers:{apikey:health.auth.anonKey,Authorization:'Bearer '+token},cache:'no-store',credentials:'omit',signal:AbortSignal.timeout(10000)});const user=r.ok?await r.json():{};if(!user.email_confirmed_at||user.email?.toLowerCase()!==callbackEmail.toLowerCase()){signout();fail('needLogin');}callbackEmail='';}syncSigned();if(token)await prefs();}}
  overlay.addEventListener('click',e=>{if(e.target===overlay)close();});overlay.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();close();}if(e.key==='Tab'){const all=Array.from(panel.querySelectorAll('button,input,select,textarea,a[href]')).filter(el=>!el.disabled&&el.getClientRects().length);const first=all[0],last=all.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
  function mount(){const box=$('personalAISettings');if(!box)return;box.className='personal-ai-settings';box.replaceChildren(mk('strong',tr('title')),mk('p',tr('disabled')),action(tr('open'),open));}
  build();mount();document.addEventListener('click',e=>{if(e.target.closest('[data-personal-ai="analyze"]'))run(open);});window.addEventListener('starnews:locale',()=>{build();mount();if(health){$('personalAIAuth').hidden=false;$('personalAIPool').textContent=tr(health.publicPool?'pool':'noPool');syncSigned();if(token)run(prefs);}});window.addEventListener('pagehide',signout);
  if(token&&endpoint)run(open);
})();
