/* In-page provider setup guidance only. No network, keys, OAuth, native launch or storage. */
(()=>{'use strict';
const guides=Object.freeze({grok:'https://docs.x.ai/build/cli/headless-scripting',claude:'https://code.claude.com/docs/en/legal-and-compliance',deepseek:'https://api-docs.deepseek.com/',qianwen:'https://www.alibabacloud.com/help/en/model-studio/get-api-key',doubao:'https://www.volcengine.com/docs/82379',kimi:'https://platform.moonshot.cn/docs',zhipu:'https://docs.bigmodel.cn/',yuanbao:'https://yuanbao.tencent.com/'});
const copy={
'zh-CN':['选择接入方式','官方网页 · 手动交接可用','标准 API · 尚未连接','官方本机客户端 · 尚未启用','在本人官方网页完成问答，再自行导回。星闻不会读取网站登录或自动发送材料。','响应适配代码已具备；尚未接入实际请求。需要本人另行确认标准 API 计费、模型和调用预算，以及专用密钥保存/删除方式。不使用 Coding Plan。','本机调用契约已核对；客户端、本人登录和权限边界尚未完成验证。需要另行批准具体官方客户端及调用；星闻不接管订阅凭据。','接入地区','请选择地区','中国大陆 · 北京','新加坡','准备本页草案','草案已准备，仍未连接；没有密钥或实际请求。','清除本页接入草案','本页草案已清除；未保存密钥，也未撤销任何官方账户。','查看此厂商官方说明','使用手动交接','请先选择与未来标准 API 密钥一致的地区。','无需密钥的步骤可现在准备。草案仅在本页，切换 profile 或退出会清除。','网页交接不等于账户绑定。','仅有官方网页交接；本机/API 接入未实现。','千问连接前还需按控制台核实地区和接口。现有适配不代表所有新功能均已支持。'],
'zh-TW':['選擇接入方式','官方網頁 · 手動交接可用','標準 API · 尚未連接','官方本機用戶端 · 尚未啟用','在本人官方網頁完成問答，再自行匯回。星聞不會讀取網站登入或自動傳送材料。','回應適配程式已具備；尚未接入實際請求。需要本人另行確認標準 API 計費、模型與呼叫預算，以及專用金鑰保存/刪除方式。不使用 Coding Plan。','本機呼叫契約已核對；用戶端、本人登入與權限邊界尚未完成驗證。須另行批准具體官方用戶端與呼叫；星聞不接管訂閱憑據。','接入地區','請選擇地區','中國大陸 · 北京','新加坡','準備本頁草案','草案已準備，仍未連接；沒有金鑰或實際請求。','清除本頁接入草案','本頁草案已清除；未保存金鑰，也未撤銷任何官方帳戶。','查看此廠商官方說明','使用手動交接','請先選擇與未來標準 API 金鑰一致的地區。','無需金鑰的步驟可現在準備。草案僅在本頁，切換 profile 或退出會清除。','網頁交接不等於帳戶綁定。','僅有官方網頁交接；本機/API 接入未實作。','千問連接前還須按控制台核實地區與介面。現有適配不代表所有新功能均已支援。'],
ja:['接続方法を選ぶ','公式ウェブ · 手動引き渡しを利用可能','標準 API · 未接続','公式端末クライアント · 未有効化','本人の公式サイトで質問し、回答を自分で戻します。星聞はサイトのログインを読み取らず、資料を自動送信しません。','応答の処理コードはありますが、実際の送信は未接続です。標準 API の課金、モデル、呼び出し予算と専用キーの保存・削除について個別認可が必要です。Coding Plan は使いません。','端末呼び出しの仕様を確認済みです。クライアント、本人ログイン、権限の実動作は未検証です。公式クライアントと呼び出しの個別認可が必要です。購読用認証情報は預かりません。','接続リージョン','リージョンを選ぶ','中国本土 · 北京','シンガポール','このページで下書きを準備','下書きのみ準備済み・未接続。キーも実際の送信もありません。','このページの接続下書きを消去','下書きを消去しました。キーは保存しておらず、公式アカウントの失効操作もしていません。','この提供元の公式ガイド','手動引き渡しを使う','今後使う標準 API キーと同じリージョンを選んでください。','キー不要の準備だけ行えます。下書きはこのページ内だけで、profile の切り替えや退出で消去します。','ウェブでの引き渡しはアカウント連携ではありません。','公式ウェブへの引き渡しのみ。端末/API 接続は未実装です。','Qwen は接続前にコンソールでリージョンとエンドポイントの確認が必要です。既存の処理はすべての新機能への対応を保証しません。'],
en:['Choose a connection method','Official website · manual handoff available','Standard API · not connected','Official native client · not enabled','Ask in your own official website, then bring the answer back yourself. Starnews does not read its login or send material automatically.','Response adapter code exists, but live requests are not wired. Separate approval is needed for standard API billing, model and request budget, plus dedicated key storage/deletion. Coding Plan is not used.','Native invocation contracts were checked. The client, your login and actual permission boundaries remain unverified. A specific official client and invocation need separate approval; Starnews does not take subscription credentials.','Connection region','Choose a region','Mainland China · Beijing','Singapore','Prepare this page’s draft','Draft prepared; still not connected. No key or live request.','Clear this page’s setup draft','Draft cleared. No key was stored and no official account was revoked.','This provider’s official guide','Use manual handoff','Choose the region matching the future standard API key first.','Prepare only steps that need no key. Drafts stay in this page and clear on profile switch or exit.','Website handoff does not bind an account.','Official website handoff only; native/API connection is not implemented.','Before connecting Qwen, verify the region and endpoint in its console. The existing adapter does not cover every new feature.']};
let owner=null,draft=null,selection={provider:'',route:'web',region:''},status=null,host=null;
const profile=()=>window.StarnewsProfiles?.active()?.id||null,locale=()=>window.StarnewsBridge?.getLocale?.()||document.documentElement.lang||'en',t=i=>(copy[locale()]||copy.en)[i];
function options(provider){if(!Object.hasOwn(guides,provider))return [];return ['web',...(['deepseek','qianwen'].includes(provider)?['api']:[]),...(['claude','grok'].includes(provider)?['native']:[])];}
function plan(provider,region=''){if(!['deepseek','qianwen'].includes(provider)||provider==='qianwen'&&!['beijing','singapore'].includes(region)||provider==='deepseek'&&region)throw Error('invalid_plan');return Object.freeze({provider,route:'standard_api',region,connected:false,state:'draft_only',requiresSeparateApproval:true});}
function reset(){draft=null;selection={provider:'',route:'web',region:''};status=null;owner=profile();host?.replaceChildren();host=null;}
function valid(provider){if(owner!==profile()){reset();return false;}return selection.provider===provider;}
function manual(provider){if(!valid(provider))return;const select=document.getElementById('personalAIHandoffProvider'),fallback=document.querySelector('details.personal-ai-fallback');if(!select||!fallback)return;if(select.value!==provider){select.value=provider;select.dispatchEvent(new Event('change'));}fallback.open=true;fallback.scrollIntoView?.({block:'nearest'});document.getElementById('personalAIHandoffQuestion')?.focus();}
function render(section,provider){if(!Object.hasOwn(guides,provider))return;if(owner!==profile()){reset();owner=profile();}if(selection.provider!==provider){draft=null;selection={provider,route:'web',region:''};status=null;}section.querySelector('#providerSetup')?.remove();const box=document.createElement('div');box.id='providerSetup';box.className='provider-setup';host=box;const e=(tag,text)=>{const x=document.createElement(tag);if(text)x.textContent=text;return x;};box.append(e('h4',t(0)));const label=e('label',t(0)),routes=e('select');routes.id='providerSetupRoute';for(const route of options(provider)){const option=e('option',t({web:1,api:2,native:3}[route]));option.value=route;routes.append(option);}routes.value=selection.route;label.append(routes);box.append(label);routes.onchange=()=>{if(!valid(provider))return;draft=null;selection.route=routes.value;selection.region='';status=null;render(section,provider);};const description=selection.route==='api'?t(5):selection.route==='native'?t(6):t(4)+' '+t(19);box.append(e('p',description));if(selection.route==='api'){if(provider==='qianwen'){const l=e('label',t(7)),r=e('select');r.id='providerSetupRegion';for(const [value,index] of [['',8],['beijing',9],['singapore',10]]){const o=e('option',t(index));o.value=value;r.append(o);}r.value=selection.region;r.onchange=()=>{if(!valid(provider))return;selection.region=r.value;draft=null;status=null;box.querySelector('#providerSetupState').textContent=t(2);};l.append(r);box.append(l,e('p',t(21)));}const prepare=e('button',t(11));prepare.type='button';prepare.id='providerSetupPrepare';prepare.onclick=()=>{if(!valid(provider))return;try{draft=plan(provider,selection.region);status=12;}catch{status=17;}render(section,provider);};box.append(prepare,e('p',t(18)));}if(options(provider).length===1)box.append(e('p',t(20)));const notice=e('p',t(status===null?(selection.route==='web'?19:selection.route==='api'?2:3):status));notice.id='providerSetupState';notice.setAttribute('role','status');box.append(notice);const guide=e('a',t(15));guide.id='providerSetupGuide';guide.href=guides[provider];guide.target='_blank';guide.rel='noopener noreferrer';box.append(guide);const handoff=e('button',t(16));handoff.type='button';handoff.id='providerSetupManual';handoff.onclick=()=>manual(provider);const clear=e('button',t(13));clear.type='button';clear.id='providerSetupClear';clear.onclick=()=>{if(!valid(provider))return;draft=null;selection.region='';selection.route='web';status=14;render(section,provider);};box.append(handoff,clear);section.append(box);}
window.StarnewsProviderSetup=Object.freeze({mount:render,reset,options,plan,guide:provider=>guides[provider]||null});window.addEventListener('starnews:session-exit',reset);window.addEventListener('pagehide',reset);window.addEventListener('storage',e=>{if(e.key==='starnews:profiles:v1')reset();});
})();
