const assert=require('node:assert/strict'),{chromium}=require('playwright'),fs=require('node:fs');
const base=process.argv[2]||'http://127.0.0.1:8877';
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
for(const locale of ['zh-CN','zh-TW','ja','en']){
 const context=await browser.newContext({locale,viewport:{width:390,height:844},serviceWorkers:'block',reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const archive=JSON.parse(fs.readFileSync('archive-stories.json','utf8')),edition=structuredClone(archive.editions.find(e=>e.locale===locale));
 const parts=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const part=k=>parts.find(x=>x.type===k).value;edition.date=part('year')+'-'+part('month')+'-'+part('day');edition.session='morning';edition.generated_at=new Date().toISOString();
 const main=edition.items[0];main.event={independently_verified:false,sources:[{...main.source,title:main.title,excerpt:'Attributed source material.',language:'en'},{name:'Fixture second source',url:'https://example.org/report',title:main.title,excerpt:'A separately attributed excerpt, not a cross-verification claim.',language:'en',published_at:edition.generated_at}]};
 edition.briefs=[{id:'brief',title:'Short source headline',summary:'Only a short source excerpt.',source:{name:'Fixture short source',url:'https://example.org/brief',language:'en'},category:'world',localized:{[locale]:{title:'Short source headline',summary:'Only a short source excerpt.',language:'en',status:locale==='en'?'original':'fallback'}}}];
 let changed=false;
 await page.route('**/ai-briefs.json',route=>{const e=structuredClone(edition);if(changed){e.items[0].title+=' · UPDATED';delete e.items[0].localized;}return route.fulfill({json:{schema:1,editions:[e]}})});
 await page.goto(base);await page.locator('[data-action=onboarding-skip]').click();await page.waitForFunction(()=>document.querySelector('#heroHeadline').textContent.includes('SpaceX'));
 assert.equal(await page.locator('#briefList details').count(),1);await page.locator('#briefList summary').click();assert((await page.locator('#briefList').innerText()).includes('Only a short source excerpt.'));
 await page.locator('[data-action=open-reader]').click();await page.waitForTimeout(100);assert.equal(await page.locator('.event-source').count(),2);assert.equal(await page.locator('#readerSources a').count(),2);
 await page.locator('.reader-scroll').evaluate(e=>e.scrollTop=(e.scrollHeight-e.clientHeight)*.55);await page.waitForTimeout(240);const ratio=await page.locator('.reader-scroll').evaluate(e=>e.scrollTop/(e.scrollHeight-e.clientHeight));assert(ratio>.5);
 await page.keyboard.press('Escape');await page.locator('[data-action=open-reader]').click();await page.waitForTimeout(100);assert(Math.abs(await page.locator('.reader-scroll').evaluate(e=>e.scrollTop/(e.scrollHeight-e.clientHeight))-ratio)<.03,'Reopen restores position');
 await page.keyboard.press('Escape');await page.reload();await page.waitForFunction(()=>document.querySelector('#heroHeadline').textContent.includes('SpaceX'));await page.locator('[data-action=open-reader]').click();await page.waitForTimeout(100);assert(Math.abs(await page.locator('.reader-scroll').evaluate(e=>e.scrollTop/(e.scrollHeight-e.clientHeight))-ratio)<.03,'Reload restores position');
 // Font and viewport changes preserve fractional location rather than old pixels.
 await page.keyboard.press('Escape');await page.setViewportSize({width:1024,height:768});await page.locator('[data-action=open-reader]').click();await page.waitForTimeout(100);assert(Math.abs(await page.locator('.reader-scroll').evaluate(e=>e.scrollTop/(e.scrollHeight-e.clientHeight))-ratio)<.03);
 await page.locator('[data-action=restart-reading]').click();assert.equal(await page.locator('.reader-scroll').evaluate(e=>e.scrollTop),0);
 await page.locator('.reader-scroll').evaluate(e=>e.scrollTop=700);await page.waitForTimeout(240);await page.keyboard.press('Escape');changed=true;await page.reload();await page.waitForFunction(()=>document.querySelector('#heroHeadline').textContent.includes('UPDATED'));await page.locator('[data-action=open-reader]').click();await page.waitForTimeout(100);assert.equal(await page.locator('.reader-scroll').evaluate(e=>e.scrollTop),0,'Changed content resets location');
 await page.locator('.reader-scroll').evaluate(e=>e.scrollTop=900);await page.waitForTimeout(240);await page.keyboard.press('Escape');await page.locator('[data-action=settings]').click();await page.locator('#privateModeToggle').check();assert.equal(await page.evaluate(()=>localStorage.getItem('starnews:reading-positions:v1')),null);await page.keyboard.press('Escape');await page.locator('[data-action=open-reader]').click();await page.locator('.reader-scroll').evaluate(e=>e.scrollTop=1100);await page.waitForTimeout(240);assert.equal(await page.evaluate(()=>localStorage.getItem('starnews:reading-positions:v1')),null,'Temporary mode leaves no history');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({locale,result:'passed',cases:'brief rail, attributed sources, reopen/reload/resize progress, changed content, reset, temporary privacy'}));await context.close();
}
const c=await browser.newContext({locale:'en',serviceWorkers:'block'}),p=await c.newPage(),emptyErrors=[];p.on('pageerror',e=>emptyErrors.push(e.message));await p.route('**/ai-briefs.json',r=>r.fulfill({json:{schema:1,editions:[{locale:'en',date:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo'}).format(new Date()),session:'morning',generated_at:new Date().toISOString(),items:[],briefs:[{title:'Brief-only edition',summary:'No reliable long text.',source:{name:'Fixture',url:'https://example.org/brief',language:'en'}}]}]}}));await p.goto(base);await p.locator('[data-action=onboarding-skip]').click();await p.locator('[data-edition-choice=morning]').click();await p.waitForTimeout(150);assert(await p.locator('#hero').isHidden(),'No old morning filler');assert(await p.locator('#briefDesk').isVisible(),'Brief-only edition remains useful');await p.locator('[data-action=settings]').click();await p.locator('#languageSelect').selectOption('ja');await p.keyboard.press('Escape');assert(await p.locator('#hero').isHidden());assert(await p.locator('#briefDesk').isHidden(),'Missing target-language edition must not retain old-language briefs');assert(await p.locator('#emptyEdition').isVisible());assert.deepEqual(emptyErrors,[]);await c.close();
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
