const {JSDOM}=require('jsdom'),assert=require('node:assert/strict'),fs=require('node:fs');
const code=fs.readFileSync('jma-events.js','utf8'),sample=fs.readFileSync('tests/fixtures/jma/vpww53-20261009.xml','utf8');
const url='https://www.data.jma.go.jp/developer/xml/data/20261009015806_0_VPWW53_472000.xml',feed=`<feed xmlns="http://www.w3.org/2005/Atom"><entry><updated>2026-10-09T01:58:05Z</updated><link href="${url}"/></entry></feed>`;
const area={offices:{472000:{name:'大東島地方',enName:'Daitojima'}},class10s:{472000:{parent:'472000'}},class15s:{472000:{parent:'472000'}},class20s:{4735700:{name:'南大東村',enName:'Minamidaito Village',parent:'472000'},4735800:{name:'北大東村',enName:'Kitadaito Village',parent:'472000'}}};
const tick=()=>new Promise(r=>setTimeout(r,15));
function fixture(language='en',fail=false){const dom=new JSDOM(`<html lang="${language}"><section id="jmaEvents"></section></html>`,{url:'https://mornyep.github.io/hoshi-news/',runScripts:'outside-only'}),w=dom.window,calls=[];w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.fetch=async(u,o)=>{calls.push({url:u,credentials:o.credentials,redirect:o.redirect});if(fail)throw Error('fixture failure');const body=u.endsWith('area.json')?JSON.stringify(area):u.endsWith('extra_l.xml')?feed:sample;return new Response(body,{status:200});};w.eval(code);return {dom,w,calls};}
(async()=>{
for(const language of ['zh-CN','zh-TW','ja','en']){const {dom,w,calls}=fixture(language);await tick();assert.equal(calls.length,1);assert(calls[0].url.endsWith('/area.json'));const change=(id,v)=>{const e=w.document.getElementById(id);e.value=v;e.dispatchEvent(new w.Event('change'));};change('jmaOffice','472000');change('jmaCity','4735700');w.document.getElementById('jmaRefresh').click();await tick();assert.equal(calls.length,3);assert.equal(w.document.querySelectorAll('#jmaRiskList li').length,1);assert.match(w.document.querySelector('#jmaRiskList').textContent,/雷注意報.*14.*継続/);assert.equal(w.document.querySelector('#jmaEvents a').href,url);const shown=w.document.querySelector('.jma-times').textContent;assert.match(shown,/2026-10-09T10:58:00\+09:00/);w.document.getElementById('jmaRefresh').click();await tick();assert.equal(calls.length,3);assert.equal(w.document.querySelector('.jma-times').textContent,shown);for(const c of calls){assert.equal(c.credentials,'omit');assert.equal(c.redirect,'error');}assert.equal(w.localStorage.length,0);assert.equal(w.sessionStorage.length,0);w.document.documentElement.lang=language==='en'?'ja':'en';await tick();assert.equal(calls.length,3);assert.equal(w.document.querySelector('#jmaCity').value,'4735700');const j=w.StarnewsJMA,b=j.report(sample,url,'2026-10-09T02:00:00Z');let s=j.reduce(null,b,'4735700');assert.equal(j.state(s,Date.parse('2026-10-09T04:00:00Z')),'stale');const cancelled=Object.freeze({...b,info_type:'取消',signature:'cancel',source_updated_at:'2026-10-09T02:01:00Z',risks:Object.freeze([])});s=j.reduce(s,cancelled,'4735700');assert.equal(j.state(s),'cancelled');assert.equal(s.previousRisks[0].name,'雷注意報');assert.equal(j.reduce(s,b,'4735700'),s);assert.throws(()=>j.report(sample.replace('1.1_2','9.9'),url,b.fetched_at));assert.throws(()=>j.report('<!DOCTYPE x [<!ENTITY x SYSTEM "file:///x">]><x/>',url,b.fetched_at));assert.throws(()=>j.report(sample,'https://evil.test/x.xml',b.fetched_at));await assert.rejects(j.read('https://evil.test/x.xml',100));assert.equal(j.catalogue(area).cities['4735700'].office,'472000');assert.throws(()=>j.catalogue({...area,class20s:{4735700:{name:'fake',parent:'missing'}}}));dom.window.close();}
const bad=fixture('en',true);await tick();assert.match(bad.w.document.querySelector('#jmaStatus').textContent,/catalogue failed/i);assert.equal(bad.calls.length,1);assert.equal(bad.w.document.querySelector('#jmaRefresh').disabled,true);bad.dom.window.close();
const race=fixture();await tick();const w=race.w;for(const [id,v] of [['jmaOffice','472000'],['jmaCity','4735700']]){const e=w.document.getElementById(id);e.value=v;e.dispatchEvent(new w.Event('change'));}let resolve;w.fetch=()=>new Promise(r=>resolve=r);w.document.getElementById('jmaRefresh').click();const e=w.document.getElementById('jmaCity');e.value='4735800';e.dispatchEvent(new w.Event('change'));resolve(new Response(feed));await tick();assert.equal(w.document.querySelector('#jmaRiskList'),null);assert.equal(w.document.querySelector('#jmaCity').value,'4735800');race.dom.window.close();console.log('JMA DOM: four languages, exact regions, raw risks, times, cache/throttle, cancellation, stale, unsafe XML/URLs, failure and late responses passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
