import http from 'node:http';import fs from 'node:fs/promises';import {createHash} from 'node:crypto';import path from 'node:path';import {fileURLToPath} from 'node:url';import {pairingGate} from './pairing.mjs';import {PrivateStore,profileID} from './store.mjs';import {OpenAIConnection,random} from './oauth.mjs';
export const ORIGIN='https://mornyep.github.io',PAGE=ORIGIN+'/hoshi-news/';
const tabID=v=>typeof v==='string'&&/^[a-zA-Z0-9_-]{16,100}$/.test(v);
const strict=(o,keys)=>{if(!o||typeof o!=='object'||Array.isArray(o)||Object.keys(o).some(k=>!keys.includes(k)))throw Error('invalid_fields');};
function context(o){strict(o,['profile','tab','language','provider']);if(!profileID(o.profile)||!tabID(o.tab))throw Error('invalid_context');return o;}
async function body(req,max=20000){let data='';for await(const chunk of req){data+=chunk;if(Buffer.byteLength(data)>max)throw Error('request_too_large');}return data;}
const safeError=e=>new Set(['authorization_declined','plan_permission_not_granted','identity_mismatch','reauthorization_required','initial_validation_limit','not_connected','invalid_model','incomplete_response','official_request_failed','official_rate_limited','invalid_oauth_state','invalid_oauth_client']).has(e.message)?e.message:'request_rejected';
export function createServer({store,oauth,port=45457,sessions=[]}){
 const gate=pairingGate({random,digest:v=>createHash('sha256').update(v).digest('hex')}),approvals=new Map(),active=new Map(),requests=new Set();gate.restore(sessions);let persistence=Promise.resolve();const persist=()=>{persistence=persistence.catch(()=>{}).then(()=>store.write('pairings.json',gate.dump()));return persistence;};
 const server=http.createServer(async(req,res)=>{const local='http://127.0.0.1:'+port,origin=req.headers.origin;const headers={'Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'"};if(origin===ORIGIN){headers['Access-Control-Allow-Origin']=ORIGIN;headers.Vary='Origin';}
 const json=(v,status=200)=>{res.writeHead(status,{...headers,'Content-Type':'application/json'});res.end(JSON.stringify(v));};const redirect=url=>{res.writeHead(303,{...headers,Location:url});res.end();};
 try{if(req.headers.host!=='127.0.0.1:'+port)throw Error('host_rejected');if(req.socket.remoteAddress!=='127.0.0.1'&&req.socket.remoteAddress!=='::ffff:127.0.0.1')throw Error('remote_rejected');const u=new URL(req.url,local);
 if(req.method==='OPTIONS'){if(origin!==ORIGIN)throw Error('origin_rejected');res.writeHead(204,{...headers,'Access-Control-Allow-Methods':'GET,POST','Access-Control-Allow-Headers':'Content-Type,Authorization','Access-Control-Allow-Private-Network':'true','Access-Control-Max-Age':'300'});return res.end();}
 if(u.pathname==='/health'&&req.method==='GET'){if(origin&&origin!==ORIGIN)throw Error('origin_rejected');return json({schema:1,app:'Starnews',provider:'chatgpt',transport:'loopback',authorization:'user_required',inferenceLimit:1});}
 if(u.pathname==='/connect'&&req.method==='GET'){if(origin&&origin!==ORIGIN)throw Error('origin_rejected');if([...u.searchParams.keys()].some(k=>!['profile','tab'].includes(k)))throw Error('invalid_fields');const c=context({profile:u.searchParams.get('profile'),tab:u.searchParams.get('tab')});const csrf=random();approvals.set(csrf,{context:c,expires:Date.now()+300000});res.writeHead(200,{...headers,'Content-Type':'text/html;charset=utf-8'});return res.end('<!doctype html><html lang="en"><meta name="viewport" content="width=device-width"><title>Starnews — connect ChatGPT</title><body style="font:18px system-ui;max-width:620px;margin:8vh auto;padding:24px"><h1>Continue with ChatGPT</h1><p>Starnews · this Mac only. The next page is the official OpenAI sign-in and consent page. Your dedicated credentials remain on this computer. No model request runs during sign-in.</p><p>This connection is for the Starnews profile that opened this window. It cannot connect your phone to this Mac.</p><form method="post" action="/approve"><input type="hidden" name="csrf" value="'+csrf+'"><button style="padding:14px" type="submit">Continue with ChatGPT</button></form><p>Close this window to cancel.</p></body></html>');}
 if(u.pathname==='/approve'&&req.method==='POST'){if(origin!==local)throw Error('origin_rejected');const f=new URLSearchParams(await body(req,2048)),a=approvals.get(f.get('csrf'));if(!a||a.expires<Date.now()||[...f.keys()].some(k=>k!=='csrf'))throw Error('approval_rejected');approvals.delete(f.get('csrf'));return redirect(await oauth.begin(a.context,port));}
 if(u.pathname==='/auth/callback'&&req.method==='GET'){const c=await oauth.complete(u.searchParams),code=gate.issue(c),fragment=new URLSearchParams({starnews_bridge_code:code,profile:c.profile,tab:c.tab});return redirect(PAGE+'#'+fragment.toString());}
 if(origin!==ORIGIN)throw Error('origin_rejected');if(req.method!=='POST')throw Error('method_rejected');if(!/^application\/json(?:;|$)/.test(req.headers['content-type']||''))throw Error('content_type_rejected');const data=JSON.parse(await body(req));strict(data,['context','code','request','model']);const c=context(data.context);
 if(u.pathname==='/pair'){if(typeof data.code!=='string')throw Error('invalid_fields');const token=gate.pair(origin,data.code,c);await persist();return json({token});}
 const token=(req.headers.authorization||'').replace(/^Bearer /,''),snapshot=gate.capture(origin,token,c);
 if(u.pathname==='/status'){const record=await oauth.record(c.profile);if(!gate.current(snapshot))throw Error('context_changed');if(!record)return json({connected:false,reason:'authorization_required'});const models=await oauth.models(c.profile);if(!gate.current(snapshot))throw Error('context_changed');return json({connected:true,provider:'chatgpt',accountLabel:record.email||'Verified ChatGPT account',models});}
 if(u.pathname==='/unpair'){gate.revoke(c.profile);await persist();for(const controller of active.get(c.profile)||[])controller.abort();return json({ok:true});}
 if(u.pathname==='/invalidate'){gate.change(token);await persist();for(const controller of active.get(c.profile)||[])controller.abort();return json({ok:true});}
 if(u.pathname==='/disconnect'){gate.revoke(c.profile);await persist();for(const controller of active.get(c.profile)||[])controller.abort();const confirmed=await oauth.disconnect(c.profile);return json({connected:false,localCredentialsRemoved:true,remoteRevocationConfirmed:confirmed});}
 if(u.pathname==='/ask'){if(requests.has(c.profile))throw Error('request_in_progress');const value=gate.question(data.request);if(value.language!==c.language)throw Error('invalid_context');if(typeof data.model!=='string')throw Error('invalid_model');const controller=new AbortController();requests.add(c.profile);if(!active.has(c.profile))active.set(c.profile,new Set());active.get(c.profile).add(controller);res.on('close',()=>{if(!res.writableEnded)controller.abort();});try{const answer=await oauth.ask(c.profile,{...value,model:data.model},controller.signal);if(!gate.current(snapshot))throw Error('context_changed');return json({answer,provider:'chatgpt',verifiedFacts:false});}finally{requests.delete(c.profile);active.get(c.profile)?.delete(controller);}}
 throw Error('not_found');
 }catch(e){if(!res.headersSent)json({error:safeError(e)},400);else res.end();}});
 server.on('listening',()=>{port=server.address().port;});server.headersTimeout=10000;server.requestTimeout=15000;return server;
}
if(process.argv[1]===fileURLToPath(import.meta.url)){const stateDir=process.env.STARNEWS_STATE_DIR;if(!stateDir)throw Error('STARNEWS_STATE_DIR must point to dedicated non-repository storage');const root=path.resolve(stateDir),repo=path.resolve(fileURLToPath(new URL('..',import.meta.url)));let isRepository=false;try{isRepository=(await fs.stat(path.join(repo,'.git'))).isDirectory();}catch{}if(isRepository&&(root===repo||root.startsWith(repo+path.sep)))throw Error('State must be outside source repository');const store=new PrivateStore(root);await store.init();const oauth=new OpenAIConnection({store});const server=createServer({store,oauth,sessions:await store.read('pairings.json')||[]});server.on('error',()=>{process.stderr.write('Starnews bridge could not bind its dedicated loopback port.\n');process.exitCode=1;});server.listen(45457,'127.0.0.1',()=>process.stdout.write('Starnews bridge ready at http://127.0.0.1:45457 — sign-in not started; no credentials read from Codex.\n'));}
